language: go
go:
  - 1.12

env:
  global:
    - GO111MODULE=on
#    - CC_TEST_REPORTER_ID=
#    - GITHUB_OAUTH_TOKEN=

cache:
  directories:
    - $GOPATH/pkg/mod

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go vet ./...
  - go test -cover -v ./lib -coverprofile=cover.profile

after_success:
  - ./cc-test-reporter format-coverage cover.profile --input-type gocov
  - ./cc-test-reporter upload-coverage

before_deploy:
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -pv=$(git describe --tags)

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/dist/**/*.{tar.gz,zip}
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9].*$
