language: go

go:
  - 1.12

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - go vet ./...
  - go test -v ./...
  - go build -ldflags '-w -s' .

before_deploy:
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -bc=darwin -tasks=clean-destination,xc,archive,rmbin
