language: go

go:
  - 1.12

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go vet ./...
  - go test -cover -v ./lib -coverprofile=cover.profile

after_success:
  - ./cc-test-reporter format-coverage cover.profile --input-type gocov
  - ./cc-test-reporter upload-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -bc=darwin -tasks=clean-destination,xc,archive,rmbin
